### ISSUE TITLE
undefined method `path' for {}:Hash (NoMethodError)

### ISSUE THREAD

**Issue by graceful-potato** [rswag/rswag#323]
When I try to create an integration spec using a generator for my controller, I get an error `gems/rswag-specs-2.3.1/lib/rswag/route_parser.rb:26:in `path_from': undefined method `path' for {}:Hash (NoMethodError)`

Fix - #324

**Comment by deniciocode** [comment]
Is this issue fixed? I have the same error.

**Comment by z0rk1i** [comment]
Works for **rails generate rspec:swagger API::OrdersController**
Fails with same error for **rails generate rspec:swagger API::V1::OrdersController**

**Comment by deniciocode** [comment]
@z0rk1i do you have a route for your `V1`? Do you have the same issue as mentioned in the issue for `V1`?

**Comment by graceful-potato** [comment]
@z0rk1i 
I think this means that you don't have API::OrdersController in your application or you haven't set the routes for this controller. Because when you pass a real controller to the generator, and you have routes that use that controller, an exception will be raised

And I am pretty sure that generated spec for your API::OrdersController is completely empty even if you have actions in the controller.

**Comment by z0rk1i** [comment]
Yes, it was just my mistake **rails generate rspec:swagger Api::OrdersController** works fine

**Comment by z0rk1i** [comment]
After more detailed testing I see what it works with non existing controllers and generates empty spec.
If controller with route exist - it throws mentioned error.

**Comment by jrmhaig** [comment]
I'm also seeing this. I have controllers `Reservations::V1Controller` and `Reservations::V2Controller` with routes defined as:

```ruby
  scope :api do
    namespace :reservations do
      resources :v1, param: :registration
      resources :v2, param: :registration
    end
  end
```

I get the error when I try

```bash
bundle exec rails g rspec:swagger Reservations::V1Controller
```

and I'm wondering if the `scope :api` is causing a problem, as this is adding `api/` to the path, which doesn't exist in the controller name.

**Update:** I think that this would be fixed by #352

**Comment by BookOfGreg** [comment]
Fixed by #324

**Comment by mikeheft** [comment]
I still get this error when trying to run `rails g rspec:swagger Api::V1::UsersController`. Here is the definition of my routes 
```ruby
api_version(module: 'Api::V1', header: { name: 'Accept', value: 'application/vnd.dispatchhealth.com; version=1' }, defaults: { format: :json }) do
    scope path: '/api', constraints: { format: /(json)/ } do
```

**Comment by brendonrapp** [comment]
I'm experiencing this error still. No `scope`, just nested namespaces, eg:

```
namespace :api do
  namespace :v1 do
    resources :events
  end
end
```

```
$ rails g rspec:swagger Api::V1::EventsController
Traceback (most recent call last):
        30: from /app/bin/rails:4:in `<main>'
        29: from /app/vendor/ruby/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
        28: from /app/vendor/ruby/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
        27: from /app/vendor/ruby/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
        26: from /app/vendor/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        25: from /app/vendor/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        24: from /app/vendor/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        23: from /app/vendor/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        22: from /app/vendor/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        21: from /app/vendor/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
        20: from /app/vendor/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
        19: from /app/vendor/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
        18: from /app/vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        17: from /app/vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        16: from /app/vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        15: from /app/vendor/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        14: from /app/vendor/ruby/2.6.0/gems/railties-6.0.3.4/lib/rails/generators.rb:276:in `invoke'
        13: from /app/vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        12: from /app/vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
        11: from /app/vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
        10: from /app/vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
         9: from /app/vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
         8: from /app/vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
         7: from /app/vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
         6: from /app/vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
         5: from /app/vendor/ruby/2.6.0/gems/rswag-specs-2.3.1/lib/generators/rspec/swagger_generator.rb:11:in `setup'
         4: from /app/vendor/ruby/2.6.0/gems/rswag-specs-2.3.1/lib/rswag/route_parser.rb:14:in `routes'
         3: from /app/vendor/ruby/2.6.0/gems/rswag-specs-2.3.1/lib/rswag/route_parser.rb:14:in `each_with_object'
         2: from /app/vendor/ruby/2.6.0/gems/rswag-specs-2.3.1/lib/rswag/route_parser.rb:14:in `each'
         1: from /app/vendor/ruby/2.6.0/gems/rswag-specs-2.3.1/lib/rswag/route_parser.rb:15:in `block in routes'
/app/vendor/ruby/2.6.0/gems/rswag-specs-2.3.1/lib/rswag/route_parser.rb:26:in `path_from': undefined method `path' for {}:Hash (NoMethodError)
```

**Comment by ignaciojonas** [comment]
Hi @brendonrapp, I'm having the same issue. The fix #324 works, but is not released yet. You can manually modify the file in you computer and make it work, to autogenerate the files. That worked for me....
